// DO NOT EDIT THIS FILE
// Copy it to `config.js` and edit it
window.CONFIG = {
  defaultTemplateId: 'default', //This is the default template for 2 args
  defaultAltTemplateId: 'defaultAlt', //This one for 1 arg
  templates: { //You can add static templates here
    'default': '<div class="chat-message"><div class="chat-message-body"><strong>{0}:</strong> {1}</div></div>',
    'defaultAlt': '{0}',
    'print': '<pre style="font-size: 0.85rem; color: #a0a0a0;">{0}</pre>',
    'example:important': '<h1 style="color: #51cf66;">^2{0}</h1>'
  },
  fadeTimeout: 4000,
  suggestionLimit: 5,
  style: {
    background: 'transparent',
    width: '28vw',
    height: '22vh',
  },
  themes: {
    'dark': {
      name: 'Dark (Default)',
      active: true,
      style: {
        '--chat-bg-primary': 'rgba(20, 23, 32, 0.95)',
        '--chat-bg-hover': 'rgba(30, 34, 48, 0.9)',
        '--chat-text-primary': '#e0e0e0',
        '--chat-text-secondary': '#a0a0a0',
        '--chat-border': 'rgba(80, 90, 110, 0.6)',
        '--chat-input-bg': 'rgba(30, 34, 48, 0.85)',
        '--chat-message-bg': 'rgba(40, 45, 60, 0.9)',
        '--accent-primary': '#4dabf7',
        '--accent-secondary': '#74c0fc',
      }
    },
    'darker': {
      name: 'Darker',
      style: {
        '--chat-bg-primary': 'rgba(10, 12, 16, 0.98)',
        '--chat-bg-hover': 'rgba(20, 23, 32, 0.95)',
        '--chat-text-primary': '#d0d0d0',
        '--chat-text-secondary': '#808080',
        '--chat-border': 'rgba(60, 70, 90, 0.7)',
        '--chat-input-bg': 'rgba(15, 18, 28, 0.9)',
        '--chat-message-bg': 'rgba(25, 30, 40, 0.95)',
        '--accent-primary': '#339af0',
        '--accent-secondary': '#63b6ff',
      }
    },
    'dim': {
      name: 'Dim',
      style: {
        '--chat-bg-primary': 'rgba(30, 33, 42, 0.9)',
        '--chat-bg-hover': 'rgba(40, 45, 58, 0.85)',
        '--chat-text-primary': '#c0c0c0',
        '--chat-text-secondary': '#909090',
        '--chat-border': 'rgba(100, 110, 130, 0.5)',
        '--chat-input-bg': 'rgba(35, 40, 52, 0.8)',
        '--chat-message-bg': 'rgba(45, 50, 65, 0.85)',
        '--accent-primary': '#5eb3f6',
        '--accent-secondary': '#85b8ff',
      }
    }
  }
};